language: python
python:
- '3.6'
install:
- pip install pipenv==2018.10.13
- pipenv run make install-dev
script:
- pipenv run make lint
- pipenv run make test
deploy:
  provider: pypi
  user: noobOriented
  password:
    secure: NS/1wezoLcihZcAzeZMP5lsC6guQb7n27nBPfsFxuaxz2HJJuPSUty6b1nB+uQVG8AhixjFMxAUzafP69Z9ClU849jrqCDanzsMZeffYtI9uH8t9vQWbQBjv9NU7s9UlbnFXWu1Fg0mLtavO7FkzNop3Loxhk195czdfelGjDjBdtXVotDx3JDYT+klmskUOPVD1gV56HMN6/OdSYXOykO91DX3SQiVDaKum2xIVK5qMdipR3G1mpqk2ciwCypd0CDWXNbW5lHpgY8kJ4K6vFVUi/SEvBh4EzrPw4BZ6GL8PULWYxHxMis7cp8rEzJljABRWScEqknjCeyb27Qemsa0/LcAUz4aTYHhsMjKsRn8VaE+BMopZKCQ2AGdGPr9ougB1uLpj1jVLB80XNR7BIF+JkDUs9Rv4XSvTZf7vLbaTxSyS0udJ32j5Q8ncvVwrCBmpbtm2MIeE2C6WndNhNEjFzWGLoekSzt+bT5tRAolEikho/i4fr8Zj4I7cpBxnD6rrTCjr9b6eCXdmgrsfikt9aQbNc0ICKDDSC0U5ALCzs/xRkOsIpKWULz1ZFlFe4Dasu6gEmJ9b2/XpW1pAjOJpxJNItOkEAJqx5DFUoUXjyGy4IddgBKnaqQ3gEc09n2sqsKHTRV7SXxhk+N7mlseFYXkhUYxIv03yKVHx4d0=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  true:
    tags: true
    python: 3.6
